<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $colorArr = array(
            array('name' => 'IndianRed','code' => '#CD5C5C'),
            array('name' => 'LightCoral','code' => '#F08080'),
            array('name' => 'Salmon','code' => '#FA8072'),
            array('name' => 'DarkSalmon','code' => '#E9967A'),
            array('name' => 'LightSalmon','code' => '#FFA07A'),
            array('name' => 'Crimson','code' => '#DC143C'),
            array('name' => 'Red','code' => '#FF0000'),
            array('name' => 'FireBrick','code' => '#B22222'),
            array('name' => 'DarkRed','code' => '#8B0000'),
            array('name' => 'Pink','code' => '#FFC0CB'),
            array('name' => 'LightPink','code' => '#FFB6C1'),
            array('name' => 'HotPink','code' => '#FF69B4'),
            array('name' => 'DeepPink','code' => '#FF1493'),
            array('name' => 'MediumVioletRed','code' => '#C71585'),
            array('name' => 'PaleVioletRed','code' => '#DB7093'),
            array('name' => 'Coral','code' => '#FF7F50'),
            array('name' => 'Tomato','code' => '#FF6347'),
            array('name' => 'OrangeRed','code' => '#FF4500'),
            array('name' => 'DarkOrange','code' => '#FF8C00'),
            array('name' => 'Orange','code' => '#FFA500'),
            array('name' => 'Gold','code' => '#FFD700'),
            array('name' => 'Yellow','code' => '#FFFF00'),
            array('name' => 'LightYellow','code' => '#FFFFE0'),
            array('name' => 'LemonChiffon','code' => '#FFFACD'),
            array('name' => 'LightGoldenrodYellow','code' => '#FAFAD2'),
            array('name' => 'PapayaWhip','code' => '#FFEFD5'),
            array('name' => 'Moccasin','code' => '#FFE4B5'),
            array('name' => 'PeachPuff','code' => '#FFDAB9'),
            array('name' => 'PaleGoldenrod','code' => '#EEE8AA'),
            array('name' => 'Khaki','code' => '#F0E68C'),
            array('name' => 'DarkKhaki','code' => '#BDB76B'),
            array('name' => 'Lavender','code' => '#E6E6FA'),
            array('name' => 'Thistle','code' => '#D8BFD8'),
            array('name' => 'Plum','code' => '#DDA0DD'),
            array('name' => 'Violet','code' => '#EE82EE'),
            array('name' => 'Orchid','code' => '#DA70D6'),
            array('name' => 'Magenta','code' => '#FF00FF'),
            array('name' => 'MediumOrchid','code' => '#BA55D3'),
            array('name' => 'MediumPurple','code' => '#9370DB'),
            array('name' => 'Amethyst','code' => '#9966CC'),
            array('name' => 'BlueViolet','code' => '#8A2BE2'),
            array('name' => 'DarkViolet','code' => '#9400D3'),
            array('name' => 'DarkOrchid','code' => '#9932CC'),
            array('name' => 'DarkMagenta','code' => '#8B008B'),
            array('name' => 'Purple','code' => '#800080'),
            array('name' => 'Indigo','code' => '#4B0082'),
            array('name' => 'SlateBlue','code' => '#6A5ACD'),
            array('name' => 'DarkSlateBlue','code' => '#483D8B'),
            array('name' => 'MediumSlateBlue','code' => '#7B68EE'),
            array('name' => 'GreenYellow','code' => '#ADFF2F'),
            array('name' => 'Chartreuse','code' => '#7FFF00'),
            array('name' => 'LawnGreen','code' => '#7CFC00'),
            array('name' => 'Lime','code' => '#00FF00'),
            array('name' => 'LimeGreen','code' => '#32CD32'),
            array('name' => 'PaleGreen','code' => '#98FB98'),
            array('name' => 'LightGreen','code' => '#90EE90'),
            array('name' => 'MediumSpringGreen','code' => '#00FA9A'),
            array('name' => 'SpringGreen','code' => '#00FF7F'),
            array('name' => 'MediumSeaGreen','code' => '#3CB371'),
            array('name' => 'SeaGreen','code' => '#2E8B57'),
            array('name' => 'ForestGreen','code' => '#228B22'),
            array('name' => 'Green','code' => '#008000'),
            array('name' => 'DarkGreen','code' => '#006400'),
            array('name' => 'YellowGreen','code' => '#9ACD32'),
            array('name' => 'OliveDrab','code' => '#6B8E23'),
            array('name' => 'Olive','code' => '#808000'),
            array('name' => 'DarkOliveGreen','code' => '#556B2F'),
            array('name' => 'MediumAquamarine','code' => '#66CDAA'),
            array('name' => 'DarkSeaGreen','code' => '#8FBC8F'),
            array('name' => 'LightSeaGreen','code' => '#20B2AA'),
            array('name' => 'DarkCyan','code' => '#008B8B'),
            array('name' => 'Teal','code' => '#008080'),
            array('name' => 'Aqua','code' => '#00FFFF'),
            array('name' => 'LightCyan','code' => '#E0FFFF'),
            array('name' => 'PaleTurquoise','code' => '#AFEEEE'),
            array('name' => 'Aquamarine','code' => '#7FFFD4'),
            array('name' => 'Turquoise','code' => '#40E0D0'),
            array('name' => 'MediumTurquoise','code' => '#48D1CC'),
            array('name' => 'DarkTurquoise','code' => '#00CED1'),
            array('name' => 'CadetBlue','code' => '#5F9EA0'),
            array('name' => 'SteelBlue','code' => '#4682B4'),
            array('name' => 'LightSteelBlue','code' => '#B0C4DE'),
            array('name' => 'PowderBlue','code' => '#B0E0E6'),
            array('name' => 'LightBlue','code' => '#ADD8E6'),
            array('name' => 'SkyBlue','code' => '#87CEEB'),
            array('name' => 'LightSkyBlue','code' => '#87CEFA'),
            array('name' => 'DeepSkyBlue','code' => '#00BFFF'),
            array('name' => 'DodgerBlue','code' => '#1E90FF'),
            array('name' => 'CornflowerBlue','code' => '#6495ED'),
            array('name' => 'RoyalBlue','code' => '#4169E1'),
            array('name' => 'Blue','code' => '#0000FF'),
            array('name' => 'MediumBlue','code' => '#0000CD'),
            array('name' => 'DarkBlue','code' => '#00008B'),
            array('name' => 'Navy','code' => '#000080'),
            array('name' => 'MidnightBlue','code' => '#191970'),
            array('name' => 'Cornsilk','code' => '#FFF8DC'),
            array('name' => 'BlanchedAlmond','code' => '#FFEBCD'),
            array('name' => 'Bisque','code' => '#FFE4C4'),
            array('name' => 'NavajoWhite','code' => '#FFDEAD'),
            array('name' => 'Wheat','code' => '#F5DEB3'),
            array('name' => 'BurlyWood','code' => '#DEB887'),
            array('name' => 'Tan','code' => '#D2B48C'),
            array('name' => 'RosyBrown','code' => '#BC8F8F'),
            array('name' => 'SandyBrown','code' => '#F4A460'),
            array('name' => 'Goldenrod','code' => '#DAA520'),
            array('name' => 'DarkGoldenrod','code' => '#B8860B'),
            array('name' => 'Peru','code' => '#CD853F'),
            array('name' => 'Chocolate','code' => '#D2691E'),
            array('name' => 'SaddleBrown','code' => '#8B4513'),
            array('name' => 'Sienna','code' => '#A0522D'),
            array('name' => 'Brown','code' => '#A52A2A'),
            array('name' => 'Maroon','code' => '#800000'),
            array('name' => 'White','code' => '#FFFFFF'),
            array('name' => 'Snow','code' => '#FFFAFA'),
            array('name' => 'Honeydew','code' => '#F0FFF0'),
            array('name' => 'MintCream','code' => '#F5FFFA'),
            array('name' => 'Azure','code' => '#F0FFFF'),
            array('name' => 'AliceBlue','code' => '#F0F8FF'),
            array('name' => 'GhostWhite','code' => '#F8F8FF'),
            array('name' => 'WhiteSmoke','code' => '#F5F5F5'),
            array('name' => 'Seashell','code' => '#FFF5EE'),
            array('name' => 'Beige','code' => '#F5F5DC'),
            array('name' => 'OldLace','code' => '#FDF5E6'),
            array('name' => 'FloralWhite','code' => '#FFFAF0'),
            array('name' => 'Ivory','code' => '#FFFFF0'),
            array('name' => 'AntiqueWhite','code' => '#FAEBD7'),
            array('name' => 'Linen','code' => '#FAF0E6'),
            array('name' => 'LavenderBlush','code' => '#FFF0F5'),
            array('name' => 'MistyRose','code' => '#FFE4E1'),
            array('name' => 'Gainsboro','code' => '#DCDCDC'),
            array('name' => 'LightGrey','code' => '#D3D3D3'),
            array('name' => 'Silver','code' => '#C0C0C0'),
            array('name' => 'DarkGray','code' => '#A9A9A9'),
            array('name' => 'Gray','code' => '#808080'),
            array('name' => 'DimGray','code' => '#696969'),
            array('name' => 'LightSlateGray','code' => '#778899'),
            array('name' => 'SlateGray','code' => '#708090'),
            array('name' => 'DarkSlateGray','code' => '#2F4F4F'),
            array('name' => 'Black','code' => '#000000')
        );

        foreach ($colorArr as $key => $color) {
            $data = Color::where('name', $color)->first();
            if (!$data) {
                $data = new Color;
            }
            $data->name = $color['name'];
            $data->code = $color['code'];
            $data->save();
        }
    }
}
